In [1]:
from mixclu import *


In [40]:
np.random.seed(10)
df, cat_columns, con_feats, y = get_dummy_data(50, 
                                               8, 
                                               2,
                                               centers        = 3,
                                               missing_values = None, 
                                               id_cols        = None)
df.head(10)

X0        X1  X2  X3        X4        X5        X6        X7
0 -0.000613 -0.037113   1   0  0.602197 -1.625200 -0.577438 -0.322381
1 -0.137942 -0.104871   1   0  0.663511 -1.495282 -0.278527 -0.393055
2  1.048869 -1.223108   0   1  0.779135  0.592948 -0.799968  1.561893
3  1.249108 -1.442275   0   1  0.869486  0.518838 -0.725651  1.218348
4 -1.061977  1.190309   0   1 -1.306833  0.837933  1.209192 -0.650815
5  0.154725  0.162645   1   0  0.463527 -1.459754 -0.540702 -0.659512
6  0.083269  0.095759   1   0  0.604802 -1.395475 -0.417023 -0.527783
7  0.117085 -0.040658   1   0  0.457656 -1.422874 -0.605057 -0.174865
8 -1.352409  0.981163   0   0 -1.446624  0.796105  1.571806 -0.811178
9  1.155845 -1.089573   0   1  0.953619  0.596984 -1.051614  1.056140

In [30]:
# base kmeans model

df_c     = df[con_feats]
result_a = kmeans_model(df_c, 
                         3, 
                         random_state = 0, 
                         max_iter     = 300, 
                         verbose      = 0, 
                         df_output    = True)
result_a[0].head(5)

/Users/monk/Desktop/MixClu/mixclu/models.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['clusters']   = list(clusters)


X1        X0        X7        X4        X5        X6  clusters
0 -0.037113 -0.000613 -0.322381  0.602197 -1.625200 -0.577438         2
1 -0.104871 -0.137942 -0.393055  0.663511 -1.495282 -0.278527         2
2 -1.223108  1.048869  1.561893  0.779135  0.592948 -0.799968         1
3 -1.442275  1.249108  1.218348  0.869486  0.518838 -0.725651         1
4  1.190309 -1.061977 -0.650815 -1.306833  0.837933  1.209192         0

In [41]:
# base kmeans one hot model

result_b = kmeans_onehot_mix(df, 
               cat_columns, 
               3,
               random_state = 0,
               max_iter     = 300, 
               verbose      = 0, 
               df_output    = False,
               scale        = None)

In [47]:
result_b['clusters']  == y

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [48]:
# base kmeans one hot model 

result_b1 = kmeans_onehot_mix(df, 
               cat_columns, 
               3,
               random_state = 0,
               max_iter     = 300, 
               verbose      = 0, 
               df_output    = False,
               scale        = 'standard')

result_b1['clusters']  == y

scaler : standard


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [50]:
# base kmeans one hot model 

result_b2 = kmeans_onehot_mix(df, 
               cat_columns, 
               3,
               random_state = 0,
               max_iter     = 300, 
               verbose      = 0, 
               df_output    = False,
               scale        = 'minmax')

result_b2['clusters']  == y

scaler : minmax


array([False, False, False, False,  True, False, False, False,  True,
       False,  True, False,  True, False, False, False,  True,  True,
        True, False,  True, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False,  True, False,
       False,  True, False,  True, False,  True, False,  True,  True,
       False, False, False, False,  True])

In [51]:
# base kmeans one hot model 
result_b3 = kmeans_onehot_mix(df, 
               cat_columns, 
               3,
               random_state = 0,
               max_iter     = 300, 
               verbose      = 0, 
               df_output    = False,
               scale        = 'power')

result_b3['clusters']  == y

scaler : power


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])